# Site settings
title: "Slothy Help"
email: tristan@slothhost.com
description: "The official help center for slothhost.com"
baseurl: "/slothy-help"
url: "http://help.slothhost.com"
twitter_username: "SlothHost"
github_username:  "SlothHost"
color_theme:  "#2d374d"
color_text:  "#fff"
language:  "en"

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 5

collections:
  articles:
    output: true
    permalink: /:collection/:path/

# Plugins
plugins_dir:
  - jekyll-admin
